version: '3.7'
name: dockervue
services:
  web:
    container_name: vue_project
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
    - '8085:8080'
    volumes:
    - '..:/app'